### ISSUE TITLE
Api desativada

### ISSUE THREAD

**Issue by felps** [dadosgovbr/api-siconv#1]
A julgar pela resposta abaixo e pela indisponibilidade dos links incluídos, entendo que a API utilizada por este projeto foi desativada.

http://www.consultaesic.cgu.gov.br/busca/dados/Lists/Pedido/Item/displayifs.aspx?List=0c839f31%2D47d7%2D4485%2Dab65%2Dab0cee9cf8fe&ID=518017&ContentTypeId=0x0100AE261DF45E46AD47A7DEBCBDF8776B88

Existe alguma outra forma de utilização?

**Comment by augusto-herrmann** [comment]
Sim, a API foi desativada em 2015. Esta foi uma decisão tomada pelo então Ministério do Planejamento.

> Existe alguma outra forma de utilização?

Se desejar, ainda é possível instalar uma instância do projeto em seu próprio ambiente, bastando para isto seguir as instruções que estão no README. Os dados, entretanto, estarão desatualizados.

Caso deseje baixar [os dados atualizados](http://dados.gov.br/dataset/siconv), que estão em CSV, e atualizar [o modelo de dados](/dadosgovbr/api-siconv/blob/master/wsdasiconv/model.py) para refletir o modelo atual, sinta-se à vontade para enviar um pull request.
